# Generated by Django 4.0.6 on 2022-07-31 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accomodation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityViewpoint',
            fields=[
                ('cvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('viewpoint_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'city_viewpoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'months',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('days', models.IntegerField()),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('dest_id', models.AutoField(primary_key=True, serialize=False)),
                ('dest_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'destination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DestinationRoute',
            fields=[
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.route')),
            ],
            options={
                'db_table': 'destination_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('dest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.destination')),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
    ]
